### PR TITLE
updated ug

### PR DESCRIPTION
**Pull request by huixianc**

### CODE REVIEW

**Comment by xCelestialPhoenix** [comment]
I don't think it is necessary to state the start of day and end of day. It's kind of like common sense?

**Comment by huixianc** [comment]
> I don't think it is necessary to state the start of day and end of day. It's kind of like common sense?

I'm worried people will try to do 22:00 00:00 which wont work haha so need to state it explicitly or they'll think it's a bug

**Comment by xCelestialPhoenix** [comment]
I would prefer you mention an event cannot cross a midnight

**Comment by huixianc** [comment]
> I would prefer you mention an event cannot cross a midnight

is what i wrote okay ?

**Pull request merged**
