### PR TITLE
minimal change to Schedule classes

### PR DESCRIPTION
**Pull request by mightyrabbit99**

### CODE REVIEW

**Comment by mightyrabbit99** [comment]
1) deleteEvent implemented poorly due to constraints.
2) all schedule classes now implement Copyable.
3) getFreeSlot implemented.

**Review by huixianc — COMMENTED** [review]
Hi Ken, may I ask why you implemented the deleteEvent method? 
1. That command is not your responsibility. As per the UG, it is under the events feature, which is allocated to me. I believe that you have a delete task command under the daily study planner feature, which should be different from the event one. 
2. The implementation of deleteEvent is not as intended, in that it does not fit the command syntax. I have already implemented the command as intended (although it has not been merged yet). 
Please do remove the deleteEvent method you implemented, thank you. 

For the rest of the changes made, please wait for @xCelestialPhoenix to review them before I can determine whether to merge.

**Review by xCelestialPhoenix — COMMENTED** [review]
No modifications to my end. No objection to merge.

**Comment by mightyrabbit99** [comment]
> Hi Ken, may I ask why you implemented the deleteEvent method?
> 
>     1. That command is not your responsibility. As per the UG, it is under the events feature, which is allocated to me. I believe that you have a delete task command under the daily study planner feature, which should be different from the event one.
> 
>     2. The implementation of deleteEvent is not as intended, in that it does not fit the command syntax. I have already implemented the command as intended (although it has not been merged yet).
>        Please do remove the deleteEvent method you implemented, thank you.
> 
> 
> For the rest of the changes made, please wait for @xCelestialPhoenix to review them before I can determine whether to merge.

Done

**Comment by mightyrabbit99** [comment]
> Hi Ken, may I ask why you implemented the deleteEvent method?
> 
>     1. That command is not your responsibility. As per the UG, it is under the events feature, which is allocated to me. I believe that you have a delete task command under the daily study planner feature, which should be different from the event one.
> 
>     2. The implementation of deleteEvent is not as intended, in that it does not fit the command syntax. I have already implemented the command as intended (although it has not been merged yet).
>        Please do remove the deleteEvent method you implemented, thank you.
> 
> 
> For the rest of the changes made, please wait for @xCelestialPhoenix to review them before I can determine whether to merge.

please merge the deleteEvent asap

**Pull request merged**
