### PR TITLE
Make freeslot and planner work again

### PR DESCRIPTION
**Pull request by mightyrabbit99**
modified addEvent

### CODE REVIEW

**Review by huixianc — COMMENTED** [review]
1. As mentioned before, please do not make major changes to other people's code. It is alright to add a few lines or so, but you should not be rewriting an entire part. The event commands are not your responsibility, so I do not see why you have to make major changes to them. 
2. I do not see why events has to be a TreeSet. The LinkedList is working fine, so I think we should keep it as it is. 
3. Please do not change the WEEK_OFFSET constant. It affects the calculation of the weeks and hence makes the view week command incorrect.  
Due to the above reasons, I will not be merging this PR.

**Comment by mightyrabbit99** [comment]
> 1. As mentioned before, please do not make major changes to other people's code. It is alright to add a few lines or so, but you should not be rewriting an entire part. The event commands are not your responsibility, so I do not see why you have to make major changes to them.
> 2. I do not see why events has to be a TreeSet. The LinkedList is working fine, so I think we should keep it as it is.
> 3. Please do not change the WEEK_OFFSET constant. It affects the calculation of the weeks and hence makes the view week command incorrect.
>    Due to the above reasons, I will not be merging this PR.

1. Because I need to make my things work.
2. TreeSet so that events are arranged chronologically. Insert O(log(n)) instead of O(n) as it is presumed to be the most used command.
3. It's the WEEK_OFFSET that is wrong all along. Please do the math while coding.

**Comment by xCelestialPhoenix** [comment]
>     3. It's the WEEK_OFFSET that is wrong all along. Please do the math while coding.

I used WEEK_OFFSET because I want the weeks in schedule to align with the academic calendar. With the way we are calculating weeks now, all the dates from the first week after passing it through calWeekNumber will be 0 instead of week 1 like we would normally say. Which is why I set week offset to 1.

calWeekNumber() is meant for my own use. By changing WEEK_OFFSET, my view(weekNumber) will be affected.

**Comment by huixianc** [comment]
> 1. Because I need to make my things work.
> 2. TreeSet so that events are arranged chronologically. Insert O(log(n)) instead of O(n) as it is presumed to be the most used command.
> 3. It's the WEEK_OFFSET that is wrong all along. Please do the math while coding.

1. I do not understand why it would be necessary to make major changes to another person's code to get your own code to work? If you wish to add more methods to Schedule that's understandable but there should be no need to edit another person's methods drastically. 
2. The events were already arranged chronologically in the original code. While I understand that you are trying to "optimise" the code, it is not part of your responsibilities. I would prefer to use a List, and since I am supposed to be managing the events, I believe I have more say in what I want to use for storing the events. 
3. As mentioned by Terence, the WEEK_OFFSET affects his part, hence I cannot approve that change.

**Comment by mightyrabbit99** [comment]
> > ```
> > 3. It's the WEEK_OFFSET that is wrong all along. Please do the math while coding.
> > ```
> 
> I used WEEK_OFFSET because I want the weeks in schedule to align with the academic calendar. With the way we are calculating weeks now, all the dates from the first week after passing it through calWeekNumber will be 0 instead of week 1 like we would normally say. Which is why I set week offset to 1.
> 
> calWeekNumber() is meant for my own use. By changing WEEK_OFFSET, my view(weekNumber) will be affected.

event is added into the wrong Week object. You can set breakpoint to verify.

p/s: If your Math is not good, TreeSet and TreeMap is the thing for you. I always use them.

**Comment by huixianc** [comment]
as discussed, we will merge and make the necessary changes

**Pull request merged**
